//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sweeper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sweeper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sweeper() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sweeper.Resources.Sweeper", typeof(Sweeper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Button {
            get {
                object obj = ResourceManager.GetObject("Button", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Eight_TP {
            get {
                object obj = ResourceManager.GetObject("Eight_TP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot randomly place mines when game-board is loaded from repository..
        /// </summary>
        internal static string ExceptionCannotPlaceMinesFromBoardLoadedFromRepo {
            get {
                return ResourceManager.GetString("ExceptionCannotPlaceMinesFromBoardLoadedFromRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude point is outside the bounds of the board..
        /// </summary>
        internal static string ExceptionExcludePointIsOutOfBounds {
            get {
                return ResourceManager.GetString("ExceptionExcludePointIsOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are required to have at least 4 Game Definitions.
        /// </summary>
        internal static string ExceptionGameDefsMustHave4Definitions {
            get {
                return ResourceManager.GetString("ExceptionGameDefsMustHave4Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExceptionInvalidArguments {
            get {
                return ResourceManager.GetString("ExceptionInvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///&lt;svg
        ///    xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///    xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///    xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///    xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///    xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
        ///    xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///    xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///    xmlns:svg=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string face_grin {
            get {
                return ResourceManager.GetString("face_grin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///&lt;svg
        ///    xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///    xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///    xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///    xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///    xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
        ///    xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///    xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///    xmlns:svg=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string face_smile {
            get {
                return ResourceManager.GetString("face_smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///&lt;svg
        ///    xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///    xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///    xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///    xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///    xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
        ///    xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///    xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///    xmlns:svg=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string face_surprise {
            get {
                return ResourceManager.GetString("face_surprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///&lt;svg
        ///    xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///    xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///    xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///    xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///    xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
        ///    xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///    xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///    xmlns:svg=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string face_wink {
            get {
                return ResourceManager.GetString("face_wink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Five_TP {
            get {
                object obj = ResourceManager.GetObject("Five_TP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Flag {
            get {
                object obj = ResourceManager.GetObject("Flag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Four_TP {
            get {
                object obj = ResourceManager.GetObject("Four_TP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string GameMaxTime {
            get {
                return ResourceManager.GetString("GameMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGINNER,10,10,10|INTERMEDIATE,15,15,15|ADVANCED,20,20,20|CUSTOM,25,25,25.
        /// </summary>
        internal static string GameTypeDefs {
            get {
                return ResourceManager.GetString("GameTypeDefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Play any pieces when a mine was previously selected. .
        /// </summary>
        internal static string InvalidBoardOperationException {
            get {
                return ResourceManager.GetString("InvalidBoardOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Game must be in GameState NOT_STARTED or IN_PLAY.
        /// </summary>
        internal static string InvalidGamePlayOperationMustBeInGameStateNOT_STARTED_OR_INPLAY {
            get {
                return ResourceManager.GetString("InvalidGamePlayOperationMustBeInGameStateNOT_STARTED_OR_INPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Minesweeper_Icon {
            get {
                object obj = ResourceManager.GetObject("Minesweeper_Icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] One_TP {
            get {
                object obj = ResourceManager.GetObject("One_TP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pressed {
            get {
                object obj = ResourceManager.GetObject("Pressed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Seven_TP {
            get {
                object obj = ResourceManager.GetObject("Seven_TP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Six_TP {
            get {
                object obj = ResourceManager.GetObject("Six_TP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tango_face_grin {
            get {
                object obj = ResourceManager.GetObject("tango_face_grin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///&lt;svg
        ///    xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///    xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///    xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///    xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///    xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
        ///    xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///    xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///    xmlns:svg=&quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tango_face_sad {
            get {
                return ResourceManager.GetString("tango_face_sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tango_face_sad1 {
            get {
                object obj = ResourceManager.GetObject("tango_face_sad1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tango_face_smile {
            get {
                object obj = ResourceManager.GetObject("tango_face_smile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tango_face_surprise {
            get {
                object obj = ResourceManager.GetObject("tango_face_surprise", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tango_face_wink {
            get {
                object obj = ResourceManager.GetObject("tango_face_wink", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default, Chocolate, Copper, Key West, Powder Puff.
        /// </summary>
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Three_TP {
            get {
                object obj = ResourceManager.GetObject("Three_TP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Two_TP {
            get {
                object obj = ResourceManager.GetObject("Two_TP", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
